{% set name = "beakerx_widgets" %}
{% set version = "1.6.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/twosigma/beakerx_widgets.git
  git_tag: master

source:
  url: https://files.pythonhosted.org/packages/source/b/beakerx/{{ name }}-{{ version }}.tar.gz
  #url: file:///YOUR_LOCAL_PATH/beakerx_widgets/beakerx/dist/{{ name }}-{{ version }}.tar.gz

build:
  number: 1
  script: pip install --no-deps .
  entry_points:
  - beakerx = beakerx:run

requirements:
  build:
  - python
  - pip
  run:
  - beakerx_base={{ version }}
  - beakerx_tabledisplay={{ version }}
  - python >=3
  - notebook >=5.7.4
  - ipywidgets >=7.0
  - widgetsnbextension
  - pyspark
  - bottle
  - requests
  - numpy
  - pandas
